const INCREMENTO = 'INCREMENTO';
const DECREMENTO = 'DECREMENTO';
const INCREMENTO_IMPAR = 'INCREMENTO_IMPAR';
const INCREMENTO_ASYNC = 'INCREMENTO_ASYNC';

module.exports = {
  INCREMENTO,
  DECREMENTO,
  INCREMENTO_IMPAR,
  INCREMENTO_ASYNC
}